### ISSUE TITLE
npm install does not run for all scenarios except for the default one

### ISSUE THREAD

**Issue by nightire** [ember-cli/ember-try#207]
When I run `ember try:each`, all scenarios are fail because `npm install` does not actually run. Only the last `ember-default` scenario runs successfully.

Below is the one of the failure scenario error output:

```
=== Scenario: ember-release ====================================================


Missing npm packages:
Package: ember-source
  * Specified: https://s3.amazonaws.com/builds.emberjs.com/release/shas/8265f21b26450e78efb857846b1eaccd01ec70e3.tgz
  * Installed: (not installed)

Run `npm install` to install missing dependencies.



Stack Trace and Error Report: /var/folders/9_/y4f4n_cd5ddbzftt3x0rz19w0000gn/T/error.dump.f8c8bc9ad97edb9cd97568c31fd0219e.log
An error occurred in the constructor for ember-cli-dependency-checker at /Users/nightire/Code/very-geek/ember-plyr/node_modules/ember-cli-dependency-checker


Result: false
```

and the error log:

```
=================================================================================

ENV Summary:

  TIME: Fri Aug 31 2018 07:57:13 GMT+0800 (China Standard Time)
  TITLE: ember
  ARGV:
  - /usr/local/bin/node
  - /Users/nightire/Code/very-geek/ember-plyr/node_modules/ember-cli/bin/ember
  - exam
  - --split
  - 2
  - --parallel
  EXEC_PATH: /usr/local/bin/node
  TMPDIR: /var/folders/9_/y4f4n_cd5ddbzftt3x0rz19w0000gn/T
  SHELL: /bin/zsh
  PATH:
  - /Users/nightire/Code/very-geek/ember-plyr/node_modules/.bin
  - /Users/nightire/Code/very-geek/node_modules/.bin
  - /Users/nightire/Code/node_modules/.bin
  - /Users/nightire/node_modules/.bin
  - /Users/node_modules/.bin
  - /node_modules/.bin
  - /usr/local/bin
  - /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin
  - /Users/nightire/Code/very-geek/ember-plyr/node_modules/.bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /usr/local/opt/texinfo/bin
  - /usr/local/opt/sqlite/bin
  - /usr/local/opt/openssl/bin
  - /usr/local/opt/libxml2/bin
  - /usr/local/opt/gettext/bin
  - /usr/local/opt/curl/bin
  - /Users/nightire/.cargo/bin
  - /usr/local/opt/gnu-tar/libexec/gnubin
  - /usr/local/Cellar/zplug/2.4.2/bin
  - /usr/local/sbin
  PLATFORM: darwin x64
  FREEMEM: 4659875840
  TOTALMEM: 17179869184
  UPTIME: 687469
  LOADAVG: 3.220703125,2.568359375,2.4423828125
  CPUS:
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.14.0
  - cldr: 33.1
  - http_parser: 2.8.0
  - icu: 62.1
  - modules: 64
  - napi: 3
  - nghttp2: 1.32.0
  - node: 10.8.0
  - openssl: 1.1.0h
  - tz: 2018e
  - unicode: 11.0
  - uv: 1.22.0
  - v8: 6.7.288.49-node.19
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: 
[31mMissing npm packages: [39m
[0mPackage: [0m[36member-source[39m
[90m  * Specified: [39m[0mhttps://s3.amazonaws.com/builds.emberjs.com/release/shas/8265f21b26450e78efb857846b1eaccd01ec70e3.tgz[0m
[90m  * Installed: [39m[0m(not installed)[0m

[31mRun `npm install` to install missing dependencies.[39m

  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: 
[31mMissing npm packages: [39m
[0mPackage: [0m[36member-source[39m
[90m  * Specified: [39m[0mhttps://s3.amazonaws.com/builds.emberjs.com/release/shas/8265f21b26450e78efb857846b1eaccd01ec70e3.tgz[0m
[90m  * Installed: [39m[0m(not installed)[0m

[31mRun `npm install` to install missing dependencies.[39m

  - name: DependencyError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: [undefined]

=================================================================================
```

output of `ember version`:

```
λ ember version
ember-cli: 3.3.0
node: 10.8.0
npm: 6.4.0
os: darwin x64
```

**Comment by kategengler** [comment]
`npm install` is running, but failing. There's an odd quirk where installing the release or beta tarball that has the same checksum as a published version fails. This is the same as #201

**Comment by broerse** [comment]
```
ember-cli: 3.4.3
node: 8.12.0
os: win32 x64
```
ember-try v1.0.0 and v1.1.0 still have this error if you run `ember try:each` after `ember addon x-x`. It is solved by reverting back to ember-try v0.2.23

**Comment by kategengler** [comment]
@broerse Can you add your `npm` version?

**Comment by broerse** [comment]
@kategengler I have npm 6.4.1

**Comment by broerse** [comment]
@kategengler It also fails on Travis if I only go to the new ember-try on https://github.com/martinic/ember-simple-auth-pouch

**Comment by backspace** [comment]
This happened to me with `travis-web`; we have a daily cron build that [runs against the latest betas of Ember and Ember Data](https://github.com/travis-ci/travis-web/commit/889fb9db2e1ed5b7e48c3c4e20fafae3ece207df). I accepted a [Greenkeeper pull request](https://github.com/travis-ci/travis-web/pull/1819) with the new `ember-try` version because the tests passed, but we only use `ember-try` in the cron build so I didn’t notice the failure until the next day.

[Here](https://travis-ci.org/travis-ci/travis-web/jobs/433639308#L498)’s an example failure on npm 6.4.1. I was able to reproduce it locally. More details about the environment for that job:

```
ember-cli: 3.4.2
node: 10.7.0
npm: 6.4.1
os: Ubuntu 14.04.5 LTS
```

 I rolled back to the older version [here](https://github.com/travis-ci/travis-web/pull/1821) and the [next cron build](https://travis-ci.org/travis-ci/travis-web/builds/434216073) passed.

**Comment by adrigzr** [comment]
This issue is still happening to me. Any news?

**Comment by kategengler** [comment]
We believe we've fixed this by changing the way Ember publishes builds to s3 (for use in ember-try among other places. 

Can you confirm this is fixed?

**Comment by backspace** [comment]
I just tried it locally with `travis-web` on `ember-try` 1.1.0 and the same thing happened. I used both the `ember-beta` and `ember-data-beta` [scenarios](https://github.com/travis-ci/travis-web/blob/889fb9db2e1ed5b7e48c3c4e20fafae3ece207df/config/ember-try.js).

The log seems not that useful but here’s the one for `ember-beta`:
<details><summary>log</summary><pre>
=================================================================================

ENV Summary:

  TIME: Wed Dec 19 2018 15:47:31 GMT-0600 (Central Standard Time)
  TITLE: ember
  ARGV:
  - /usr/local/Cellar/nvm/0.33.11/versions/node/v10.7.0/bin/node
  - /Users/b/Documents/Travis/t3/node_modules/ember-cli/bin/ember
  - test
  EXEC_PATH: /usr/local/Cellar/nvm/0.33.11/versions/node/v10.7.0/bin/node
  TMPDIR: /var/folders/33/f95011rs65z83zr5sqncbtsm0000gs/T
  SHELL: /bin/zsh
  PATH:
  - /Users/b/Documents/Travis/t3/node_modules/.bin
  - /Users/b/Documents/Travis/node_modules/.bin
  - /Users/b/Documents/node_modules/.bin
  - /Users/b/node_modules/.bin
  - /Users/node_modules/.bin
  - /node_modules/.bin
  - /usr/local/Cellar/nvm/0.33.11/versions/node/v10.7.0/bin
  - /usr/local/opt/nvm/versions/node/v10.7.0/bin
  - /usr/local/heroku/bin
  - /Users/b/.yarn/bin
  - /Users/b/.rbenv/bin
  - /usr/local/opt/rbenv/shims
  - /Applications/Postgres.app/Contents/Versions/9.3/bin
  - /usr/local/share/npm/bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /usr/local/bin
  - /usr/X11/bin
  - /Users/b/.cabal/bin
  - /Users/b/bin
  - /usr/local/opt/rbenv/shims
  - /usr/local/opt/rbenv/bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /usr/local/MacGPG2/bin
  - /opt/X11/bin
  - /Applications/Postgres.app/Contents/Versions/latest/bin
  - /Users/b/Documents/Travis/trvs/bin
  PLATFORM: darwin x64
  FREEMEM: 1054871552
  TOTALMEM: 17179869184
  UPTIME: 260229
  LOADAVG: 33.3984375,37.673828125,38.1142578125
  CPUS:
  - Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz - 3500
  - Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz - 3500
  - Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz - 3500
  - Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz - 3500
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.14.0
  - cldr: 33.1
  - http_parser: 2.8.0
  - icu: 62.1
  - modules: 64
  - napi: 3
  - nghttp2: 1.32.0
  - node: 10.7.0
  - openssl: 1.1.0h
  - tz: 2018e
  - unicode: 11.0
  - uv: 1.22.0
  - v8: 6.7.288.49-node.15
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: 
[31mMissing npm packages: [39m
[0mPackage: [0m[36member-source[39m
[90m  * Specified: [39m[0mbeta[0m
[90m  * Installed: [39m[0m(not installed)[0m

[31mRun `npm install` to install missing dependencies.[39m

  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: 
[31mMissing npm packages: [39m
[0mPackage: [0m[36member-source[39m
[90m  * Specified: [39m[0mbeta[0m
[90m  * Installed: [39m[0m(not installed)[0m

[31mRun `npm install` to install missing dependencies.[39m

  - name: DependencyError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: [undefined]

=================================================================================
</pre>
</details>

Let me know if there’s anything else I can provide!

**Comment by kategengler** [comment]
@backspace I think the issue with travis-web may be different than the main issue here. 

The main issue (we think we've fixed) was a problem where the s3 builds failed to install, but the configuration for `travis-web` is using 'beta' which should be the npm `dist-tag`. Can you see if commit `e12c4ca` of ember-try works? That commit is just before a change of which I am suspicious.

**Comment by kategengler** [comment]
Either way, using the dist-tag as a version in ember-try should definitely continue to work. @backspace I'd definitely appreciate a separate issue but I can also open it with the info here.

**Comment by gorner** [comment]
I'm still having the same issue running ember-try@1.1.0 locally. I am not using any form of Travis.

**Comment by mansona** [comment]
@gorner that issue is actually related to https://github.com/ember-cli/ember-try/issues/167 and is hopefully going to be fixed when https://github.com/ember-cli/ember-try/pull/281 is merged and released 👍
